#!/usr/bin/env bash
  #===============================================
  # Project: zerotier-connect_v0.7.2 / patch #6
  # Author:  ConzZah / ©️ 2024
  # Last Modification: 18.10.24 / 21:37
  # https://github.com/ConzZah/ZeroTierConnect
  #===============================================
# important vars:
_doso="sudo"; _ztc="zerotier-cli"; _j="join"; _l="leave"; _lnw="listnetworks"
_qrencode="qrencode"; _dmsg="[ ~~~ DONE ~~~ ]"; t1="~~~~~~~~~~~~~~~~~~"; _utf="UNABLE TO FETCH."
_cr='\033[0m'; red='\033[0;31m'; green='\033[0;32m'; blue='\033[0;34m' # <-- basic colors
# set paths: 
_home="/home/$USER"; [ "$EUID" -eq 0 ] && _home="/root" # <-- if EUID is 0 change $_home from "/home/$USER" to "/root" ( meaning: you'll have a seperate savedir if ran as root or with sudo)
_SAVEDIR="$_home/ZTC_Save/SAVED_NETWORKS"; mkdir -p "$_SAVEDIR"; cd "$_SAVEDIR"
_LCNDIR="$_home/ZTC_Save/.LCN"; mkdir -p "$_LCNDIR"
# determine package manager & set options where needed:
i=0; bin=("apt" "apk" "dnf" "yum" "pacman" "zypper" "brew"); pm=""; while [ $i -lt ${#bin[@]} ]; do
if type -p "${bin[$i]}" > /dev/null; then pm="${bin[$i]}"; _add="$pm install"; break; fi; ((i++)); done
if [[ "$pm" == "apk" ]]; then ! type -p sudo > /dev/null && _doso="doas"; _add="apk add"; _qrencode="libqrencode-tools"; fi
if [[ "$pm" == "pacman" ]]; then _add="pacman -S"; fi
# check4installed_client <-- ( checks if zerotier is installed )
function check4installed_client { ! $_doso $_ztc -v >/dev/null 2>&1 && [ ! -f /usr/sbin/zerotier-one ] && ask2install_zerotier_client || : ;}
# check_deps <-- installs dependencies if they're missing.
function check_deps { echo "CHECKING FOR MISSING DEPENDENCIES.."
! type -p qrencode > /dev/null && $_doso $_add $_qrencode
! type -p curl > /dev/null && $_doso $_add curl
! type -p sed > /dev/null && $_doso $_add sed
clear ;}
# ask2install_zerotier_client <--  ( asks user if they want to install the zerotier client if it hasnt been detected. )
function ask2install_zerotier_client {
echo -e "[ [ERROR]: ZEROTIER CLIENT COULD NOT BE FOUND. ]\n"
echo "Y) INSTALL ZEROTIER"; echo "Q) EXIT"; echo ""; read -r ask2installZT
case $ask2installZT in
	Y|y) zt_installer;;
	q|Q) echo ""; echo "// EXIT"; exit;;
	*) clear; ask2install_zerotier_client
esac
}
# zt_installer <-- ( downloads & installs zerotier client binarys through https://www.zerotier.com/download/. Also, if you're on Alpine Linux, it will ask you to build from source. )
function zt_installer {
if [[ "$pm" == "apk" ]]; then clear; echo "ALPINE DETECTED"; echo ""; ask2compile4alpine; fi
_dlmsg="[ ::: DOWNLOADING & INSTALLING ZEROTIER, PLEASE WAIT.. ::: ]"; ZT_done_msg="[ ZEROTIER INSTALL FINISHED. PRESS ANY KEY TO LAUNCH ZTC ]"
echo ""; echo "$_dlmsg"; echo ""; ZTinstall=$(curl -s https://install.zerotier.com | $_doso bash) # default install through official script
echo ""; echo "$ZT_done_msg"; echo ""; read -r -n 1 -s; start_ztc
}
function ask2compile4alpine {
echo "Do you want to start building the ZeroTier Client from Source?"; echo ""; echo "( BE AWARE: This could take some time. )"; echo ""
echo "Y) BUILD FROM SOURCE"; echo "Q) EXIT"; read -r ask2compile4alpine
case $ask2compile4alpine in 
	Y|y) echo ""; compile4alpine;;
	q|Q) echo ""; echo "// EXIT"; exit;;
	*) clear; echo "ALPINE DETECTED"; echo ""; ask2compile4alpine
esac
}
function compile4alpine {
wd=$(pwd); cd /$_home; mkdir -p ZeroTier_AutoCompile-Alpine; cd ZeroTier_AutoCompile-Alpine # creates build directory
doas apk add git wget build-base clang rust cargo make linux-headers openssl-dev # installs dependencies for zerotier compilation
git clone https://github.com/zerotier/ZeroTierOne; cd ZeroTierOne # clones zerotier-one from github
doas make && echo ""; echo "DONE COMPILING!"; echo ""; echo "ENTER PASSWORD TO INSTALL ZEROTIER"; echo ""; # runs make and shows message when done
doas make install && echo ""; echo "DONE INSTALLING, SETTING UP INIT SCRIPT.."; echo "" # runs make install and shows message when done
cd /$_home; doas rm -rf ZeroTier_AutoCompile-Alpine # removes working dir to save space 
cd /etc/init.d; doas wget -q -O zerotier-one https://raw.githubusercontent.com/ConzZah/ZeroTier_AutoCompile-Alpine/main/zerotier-one.initd; doas chmod 755 zerotier-one; cd $wd # installs init script
echo "tun" > zerotier-one.conf; doas mv -f zerotier-one.conf /usr/lib/modules-load.d/; doas modprobe tun; lsmod | grep tun
doas rc-update add zerotier-one; doas rc-service zerotier-one start # adds zerotier-one service and starts it. 
doas zerotier-one -d >/dev/null 2>&1; sleep 3; echo ""; echo ""; echo "[ PRESS ANY KEY TO START ZTC ]"; echo ""; read -r -n 1 -s; start_ztc
}
# Logo
function Logo { clear
echo "   .:*======= ConzZah's =======*:."
echo " $t1$t1"
echo " *     ZEROTIER-CONNECT v0.7.2      *"
echo " $t1$t1"
status_screen
}
# status_screen
function status_screen {
if [[ "$network_state" != "OK" ]]; then stateclr="$red"; else stateclr="$_cr"; fi
if [[ "$network_name" == "$_utf" ]]; then  nameclr="$red"; else nameclr="$_cr";fi
echo "$t1$t1$t1"
echo -e "[ NETWORK ID    : $input_id ]"
echo -e "[ NETWORK ALIAS : $saved_alias ]"
echo -e "[ NETWORK NAME  : $nameclr$network_name$_cr ]"  
echo -e "[ NETWORK STATE : $stateclr$network_state$_cr ]"
echo -e "$t1$t1$t1\n"
}
# init_status
function init_status { input_id="/"; saved_alias="/"; network_name="/"; network_state="/";}
# store__current_status <-- stores current status in backup variables so we can reload them in case a user error occurs.
function store__current_status {
input_id__current=$input_id
saved_alias__current=$saved_alias
network_name__current=$network_name
network_state__current=$network_state
}
# recall__current_status <-- loads status values, previously stored with "store__current_status", back into their actual variables.
function recall__current_status {
input_id=$input_id__current
saved_alias=$saved_alias__current
network_name=$network_name__current
network_state=$network_state__current
}
# store__lcn <-- stores last connected network values in .txt files to reload them when needed.
function store__lcn { cd "$_LCNDIR"
echo "$input_id" > .lcn__input_id.txt
echo "$saved_alias" > .lcn__saved_alias.txt
echo "$network_name" > .lcn__network_name.txt
echo "$network_state" > .lcn__network_state.txt
cd $_home/ZTC_Save/
}
# recall__lcn <-- recalls last connected network values into their variables
function recall__lcn { init_status; cd "$_LCNDIR"
input_id=$(<.lcn__input_id.txt)
saved_alias=$(<.lcn__saved_alias.txt)
network_name=$(<.lcn__network_name.txt)
network_state=$(<.lcn__network_state.txt)
cd $_home/ZTC_Save/
}
# fetch_network_details <-- fetches network name, rules, status & ip 
function fetch_network_details {
[ -z $args_present ] && echo "[ /// FETCHING NETWORK DETAILS.. ]" ||:
for net in {1..4}; do network_name=$($_doso $_ztc get $input_id name); sleep 0.2; done # <-- fetching name 4 times
[ -z "$network_name" ] && network_name="$_utf"
# ^ if network name could not be fetched after 4 tries, update network_name & status_screen with: "NAME COULD NOT BE FETCHED."
{ allow_dns_status=$($_doso $_ztc get $input_id allowDNS); allow_default_status=$($_doso $_ztc get $input_id allowDefault)
allow_global_status=$($_doso $_ztc get $input_id allowGlobal); allow_managed_status=$($_doso $_ztc get $input_id allowManaged); 
ip_status=$($_doso $_ztc get $input_id ip); network_state=$($_doso $_ztc get $input_id status) network_type=$($_doso $_ztc get $input_id type) ;}
}
# if_network_not_present__fail <-- will get triggered if $input_id is set to "/" or none at all.
function if_network_not_present__fail {
error_msg="[ ~~~ [ERROR]: NO NETWORK SELECTED, TRY AGAIN. ~~~ ]"
if [[ "$input_id" == "" || "$input_id" == "/" ]]; then echo "$error_msg"; _r2main="manual"; return2main_menu; fi
}
# check4invalid__id ( check if user input given is an actual network id )
function check4invalid__id {
error_msg="[ ERROR: INVALID NETWORK ID. ]"
_check_id=$($_doso $_ztc $_j $input_id) # <-- checks if $input_id is valid by trying to join it  
if [[ "$input_id" =~ ^(q|Q)$ ]]; then recall__current_status; return2main_menu; fi  # <-- quit to main_menu during text entry: if user enters "q / Q", recall last known network values & quit to main menu
if [[ "$_check_id" == "404"* || "$_check_id" == "invalid network id" ]]; then echo "$error_msg"; __BP; echo ""; read -r -n 1 -s; recall__current_status; Logo; $back2; fi # NOTE: $back2 refers to the function that it was called from.
} 
# check4invalid__alias 
function check4invalid__alias {
_empty="[ YOU ENTERED NOTHING. ]"; doesnt_exist="[ ERROR: $saved_alias DOESN'T EXIST. ]"
if [[ "$saved_alias" =~ ^(q|Q)$ ]]; then recall__current_status; return2main_menu; fi # <-- if user enters "q", quit to main menu
if [[ "$saved_alias" == "" ]]; then echo "$_empty"; __BP; echo ""; read -r -n 1 -s; recall__current_status; Logo; $back2; fi # <-- if user enters nothing, shows error and lets them try again
if [ ! -f "$_SAVEDIR/$saved_alias.txt" ]; then echo "$doesnt_exist"; __BP; echo ""; read -r -n 1 -s; recall__current_status; Logo; $back2; fi # <-- if input does not match any saved networks, shows error and lets them try again
}
# pingtest <-- checks if your machine is connected to the internet by pinging zerotier.com before starting ztc
function pingtest {
echo "CHECKING NETWORK CONNECTION.."; echo ""; if ping -q -i 0.5 -c 2 -w 7 zerotier.com > /dev/null 2>&1; then echo "ONLINE"; clear; else 
clear; echo "YOU'RE OFFLINE. CHECK YOUR CONNECTION & TRY AGAIN."; echo ""; echo "EXITING IN 3 SECONDS.."; echo ""; sleep 3; exit; fi; }
# ztc_help <-- ZTC help / manual page
function ztc_help { cd $_home/ZTC_Save/; curl -s -L -O https://github.com/ConzZah/ZeroTierConnect/raw/main/ztc_helppage.txt; less ztc_helppage.txt; rm ztc_helppage.txt; return2main_menu; }
# gen_alias_index_txt <-- generates alias_index.txt by displaying the contents of each savefile (the network id) alongside the filename (the alias).
function gen_alias_index_txt {
_index="alias_index.txt"; _desc="       ID          ALIAS"; _error="NO NETWORKS SAVED YET."
if [ -z "$( ls "$_SAVEDIR" )" ]; then _desc="$_error"; fi; echo "$_desc"; echo "" # <-- if savefolder is empty, assign $_error to _desc
for network_alias in *.txt; do
if [[ "$_desc" == "$_error" ]]; then break; fi
network_id=$(cat "$network_alias"); echo "$network_id   $network_alias"|cut -d'.' -f1 >> raw_$_index
done; if [ -f raw_$_index ]; then sed '/^$/d' raw_$_index > $_index; cat $_index; echo ""; rm $_index; rm raw_$_index; fi
}
# Connect
function Connect {
back2="Connect"; store__current_status
cd "$_SAVEDIR"; ask4input="[  INPUT NETWORK ID OR ALIAS  ]"
echo "/// CONNECT TO ZEROTIER NETWORK "
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"; echo ""
[ -z $_ql ] && gen_alias_index_txt && echo -e "$ask4input\n" && read -r input_id || input_id=$_ql
# ^ if $_ql is empty continue as normal. if not, skip the above and copy value of $_ql to $input_id
# (note that _ql only gets set when we enter something that's less than 16 chars)
_id () {
check4invalid__id; savecheck=$(find -maxdepth 1 -name '*.txt' -exec grep -l $input_id {} +); sc="sc.txt" # ( check if entered network id is already saved and if so, load corresponding alias )
if [[ $savecheck == *"./"* ]]; then echo "$savecheck" > $sc; sed -i "s#.txt##g" $sc; sed -i "s#./##g" $sc; saved_alias=$(<$sc); rm $sc; # <-- ( loads found alias into $saved_alias )
else echo ""; echo "[ ~~~ enter alias for $input_id, to save this network ~~~ ]"; echo ""; read -r saved_alias; echo "" # <-- ( if the id should not be found in any savefile, prompt user to enter an alias & create new save entry. )
echo "$input_id" > $saved_alias.txt; echo "[ .:SAVE CREATED:. ]"; sleep 0.4; fi # <-- stores network id in .txt <-- ( writes save )
}
_alias () {
saved_alias=$input_id; check4invalid__alias # if alias was entered, check if it exists.
input_id=$(<$saved_alias.txt) # <-- loads content of $saved_alias.txt into $input_id. <-- ( loads save )
check4invalid__id # <-- makes sure that the given network id is valid, else complains.
}
if [[ ${#input_id} -eq 16 ]]; then _id; else _alias; fi # <-- decide how to handle input
echo -e "\n[ CONNECTING TO NETWORK ID: $input_id / ALIAS: $saved_alias ]\n"; echo "$t1"; $_doso $_ztc $_j $input_id; echo "$t1" # <-- connects 
fetch_network_details; store__lcn; store__current_status; return2main_menu
}
# Reconnect <-- refreshes connection to the currently selected network.
function Reconnect { if_network_not_present__fail; recall__lcn; check4invalid__id; fetch_network_details; store__lcn; echo "$_dmsg"; echo ""; return2main_menu ;}
# Disconnect
function Disconnect {
store__current_status
[ ! -z $_ql ] && cd "$SAVEDIR" && saved_alias=$_ql && check4invalid__alias && _ql=$(<$saved_alias.txt) && echo "$t1" && $_doso $_ztc $_l "$_ql" && echo "$t1" && return2main_menu
# ^ if $_ql is NOT empty, assume an alias was entered & run checks, else ignore & continue
connected_networks=$($_doso $_ztc $_lnw|sed "1d"|cut -d ' ' -f 3) # <-- get currently connected networks 
net_array=(0 $connected_networks) # <-- put them in 1 based array
count=$(echo -n "$connected_networks"| grep -c '^') # <-- count lines
[ "$count" -eq 0 ] && echo "ERROR: NO NETWORKS CONNECTED" && _r2main="manual" && return2main_menu 
echo "/// DISCONNECT FROM NETWORK"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"; echo ""
echo "$connected_networks"|nl -b a
read -r dc; case $dc in
	[1-$count]) echo "$t1"; $_doso $_ztc $_l "${net_array[$dc]}"; echo "$t1"
	if [[ "${net_array[$dc]}" == "$input_id" ]] then init_status; store__lcn; store__current_status; fi;;
	q|Q) return2main_menu;; 
	*) echo "invalid option"
esac
return2main_menu
}
# DeleteSave
function DeleteSave {
back2="DeleteSave"; store__current_status; cd "$_SAVEDIR"
echo "/// DELETE SAVE ENTRY"
echo "~~~~~~~~~~~~~~~~~~~~~~"; echo ""
gen_alias_index_txt; echo ""; echo "[ ~~~ type network alias & press [ENTER] ~~~ ]"; echo ""; read -r saved_alias; echo ""
check4invalid__alias; echo ""; echo "ARE YOU SURE YOU WANT TO DELETE $saved_alias ?"; echo ""; echo "[ Y / N ]"; echo ""; read -r DeleteSave
case $DeleteSave in
	Y|y) _dl=$(<$saved_alias.txt); $_doso $_ztc $_l $_dl >/dev/null 2>&1; rm "$saved_alias.txt"; echo -e "\n$saved_alias has been deleted."; recall__current_status
	if [[ "$_dl" == "$input_id" ]]; then init_status; store__lcn; store__current_status; _dl=""; fi; _r2main="manual"; return2main_menu ;;
	N|n) echo ""; echo "CANCELED."; echo ""; recall__current_status; return2main_menu;;
	q|Q) return2main_menu;;
	*) Logo; DeleteSave
esac 
}
# nwqr <-- creates qr code for currently selected network id ( uses local qrencode instead of qrenco.de as of v0.7.2 )
function nwqr { 
if_network_not_present__fail; echo "QR CODE FOR NETWORK ID: $input_id"; echo "";
_nwqr="https://joinzt.com/addnetwork?nwid=$input_id&v=1"
qrencode -m 2 -t utf8 <<< "$_nwqr"; echo ""; nwqr=""
_r2main="manual"; return2main_menu
}
# CheckClientInfo
function CheckClientInfo {
echo "/// CLIENT INFO"
echo "~~~~~~~~~~~~~~~~~"; echo ""
IFS=" " read -r -a _info <<< "$($_doso $_ztc info)" # <-- creates array, (uses spaces as seperator), and writes output of "sudo/doas zerotier-cli info" to said array 
echo "ZEROTIER VERSION: ${_info[3]}"; echo ""
echo "CLIENT ID: ${_info[2]}"; echo ""
echo "STATE: ${_info[4]}"; echo ""; _r2main="manual"; return2main_menu; }
# CheckConnectedNetworks
function CheckConnectedNetworks {
echo "/// CONNECTED NETWORKS"
echo "~~~~~~~~~~~~~~~~~~~~~~~"; echo ""
$_doso $_ztc $_lnw|sed 's#200 listnetworks##g'; echo ""; _r2main="manual"; return2main_menu; }
# CheckConnectedPeers
function CheckConnectedPeers {
echo "/// CONNECTED PEERS"
echo "~~~~~~~~~~~~~~~~~~~~~"
$_doso $_ztc peers|sed 's#200 peers##g'; echo ""; _r2main="manual"; return2main_menu; }
# get_net_info
function get_net_info {
if_network_not_present__fail
echo "// NETWORK INFO FOR $input_id:"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
fetch_network_details
echo -e "\nNetwork Name: $network_name\n"
echo -e "Network State: $network_state\n"
echo -e "Network Type: $network_type\n"
echo -e "Network IP: $ip_status\n"
echo -e "#### NETWORK RULES: ####\n"
echo -e "Allow DNS: $allow_dns_status\n"
echo -e "Allow Default: $allow_default_status\n"
echo -e "Allow Global: $allow_global_status\n"
echo -e "Allow Managed: $allow_managed_status\n"
_r2main="manual"; return2main_menu
}
# return2main_menu
function return2main_menu {
# defaults to auto (0.7s wait time & instant transition to main_menu)
# ^ unless _r2main="manual" is specified BEFORE return2main_menu (see get_net_info for example)
__BP; _msg_auto="[ ~~~ RETURNING TO MAIN MENU.. ~~~ ]"; _msg_manual="[ ~~~ PRESS ANY KEY TO RETURN TO MAIN MENU ~~~ ]"
if [[ "$_r2main" == "" ]]; then _r2main="sleep 0.7"; _msg="$_msg_auto"; fi # <-- auto 
if [[ "$_r2main" == "manual" ]]; then _r2main="read -r -n 1 -s"; _msg="$_msg_manual"; fi # <-- manual
echo "$_msg"; $_r2main
_msg=""; _r2main="" # <-- initializes to avoid conflicts
main_menu
}
# main_menu
function main_menu {
Logo; back2=""
echo "// MAIN MENU"
echo "~~~~~~~~~~~~~~"
echo "C)  CONNECT TO NETWORK"
echo "DC) DISCONNECT FROM NETWORK"
echo "R)  REFRESH NETWORK CONNECTION"
echo "LP) DISPLAY CONNECTED PEERS"
echo "LN) DISPLAY CONNECTED NETWORKS"
echo "I)  CURRENT NETWORK INFO"
echo "i)  ZT CLIENT INFO"
echo "H)  HELP"
echo "Q)  QUIT"
echo ""; read -r main_menu
case $main_menu in
	c|C) Logo; Connect;;
	dc|DC) Logo; Disconnect;;
	r|R) Logo; Reconnect;;
	lp|LP) Logo; CheckConnectedPeers;;
	ln|LN|listnetworks) Logo; CheckConnectedNetworks;;
	I|netstat) Logo; get_net_info;;
	i|info) Logo; CheckClientInfo;;
	dl|DL|delete) Logo; DeleteSave;;
	qr|QR) Logo; nwqr;;
	h|H|help) Logo; ztc_help;;
	q|Q|exit) echo ""; echo "// EXIT"; exit;;
	*) main_menu
esac
}
__BP () { [ ! -z $args_present ] && exit ;} # <-- (lets us exit a function early if $args_present has any value)
start_ztc () { clear; args_present=""; check_deps; check4installed_client; init_status; recall__lcn; main_menu; } # <--  start ztc in tui mode 
[ -z "$1" ] && start_ztc && exit # <-- if there are no arguments, start_ztc
[ ! -z "$1" ] && check4installed_client && args_present="x"; # <-- if there are, check4installed_client & set $args_present 
if [[ "$1" == "-j" ]]; then _ztc="$_ztc -j"; shift; fi # <-- '-j' switch (enables JSON Output, usage: ztc -j [option] [network id/alias] )
#### ARGUMENTS:
_ql="" # (note: _ql stands for both quickload and quickleave)
if [[ "$1" =~ ^(c|C|j|J|join)$ ]]; then [ ${#2} -ne 16 ] && _ql=$2 && Connect || echo "$t1"; $_doso $_ztc $_j "$2"; echo "$t1"; exit; fi; # <-- join
if [[ "$1" =~ ^(dc|DC|l|L|leave)$ ]]; then [ ${#2} -ne 16 ] && _ql=$2 && Disconnect || echo "$t1"; $_doso $_ztc $_l "$2"; echo "$t1"; exit; fi # <-- leave
if [[ "$1" =~ ^(i|info)$ ]]; then CheckClientInfo; exit; fi # <-- client info
if [[ "$1" =~ ^(ln|LN|listnetworks)$ ]]; then $_doso $_ztc $_lnw; exit; fi # <-- listnetworks
if [[ "$1" =~ ^(lp|LP|listpeers)$ ]]; then $_doso $_ztc listpeers; exit; fi # <-- listpeers
if [[ "$1" =~ ^(g|G|get)$ ]]; then $_doso $_ztc get "$2" "$3"; exit; fi # <-- get
if [[ "$1" =~ ^(s|S|set)$ ]]; then $_doso $_ztc set "$2" "$3"; exit; fi # <-- set
if [[ "$1" =~ ^(lm|LM|listmoons)$ ]]; then $_doso $_ztc listmoons; exit; fi # <-- listmoons
if [[ "$1" =~ ^(orb|orbit)$ ]]; then $_doso $_ztc orbit "$2" "$3"; exit; fi # <-- orbit
if [[ "$1" =~ ^(dorb|deorbit)$ ]]; then $_doso $_ztc deorbit "$2"; exit; fi # <-- deorbit
if [[ "$1" =~ ^(I|netstat)$ ]]; then input_id=$2; get_net_info; exit; fi # <-- network info
if [[ "$1" =~ ^(qr|QR)$ ]]; then input_id=$2; check4invalid__id; nwqr; exit; fi # <-- qr code generation
if [[ "$1" =~ ^(h|H|help)$ ]]; then ztc_help; exit; fi # <-- help page
[ ! -z "$1" ] && echo "[ ERROR: UNKNOWN OPTION. ] " && exit # <-- if nothing matched print error & exit
